
spring:

  #  RabbitMQ
  #  rabbitmq:
  #    port: 5672
  #    username: finzo
  #    password: finzo_service

  #Postgres
  datasource:
    url: jdbc:postgresql://localhost:5432/finzo_inventory_read
    username: postgres
    password: password
  #JPA
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  profiles:
    active: native
  application:
    name: inventory_read_service

  config:
    import:
      - optional:configserver:http://localhost:8988


